### ISSUE TITLE
DllNotFoundException: Unable to load DLL

### ISSUE THREAD

**Issue by leandro-almeida** [Cr3ature/HtmlToPdfConverter#1]
Hi, i'm trying to use your nuget package. I've installed the two packages: HtmlToPdfConverter and HtmlToPdfConverter.Core. I'm running on .netcore 2.2.

Added the  services.AddHtmlToPdfConverterService();

However, when i try to run, it cant find the libs:
```
An error occurred while starting the application.
DllNotFoundException: Unable to load DLL 'C:\GIT\promag\src\ProMag\TJPA.ProMag.UI.Site\bin\Debug\netcoreapp2.2\NativeLibs\X64\libwkhtmltox.dll' or one of its dependencies: Não foi possível encontrar o módulo especificado. (Exception from HRESULT: 0x8007007E)

System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(string unmanagedDllPath)

    DllNotFoundException: Unable to load DLL 'C:\GIT\promag\src\ProMag\TJPA.ProMag.UI.Site\bin\Debug\netcoreapp2.2\NativeLibs\X64\libwkhtmltox.dll' or one of its dependencies: Não foi possível encontrar o módulo especificado. (Exception from HRESULT: 0x8007007E)
        System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(string unmanagedDllPath)
        System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(string unmanagedDllPath)
        HtmlToPdfConverter.Abstractions.Configuration.ServiceCollectionExtenstion.AddHtmlToPdfConverterService(IServiceCollection services)
        TJPA.ProMag.UI.Site.Startup.ConfigureServices(IServiceCollection services) in Startup.cs

                services.AddHtmlToPdfConverterService();

Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

Inside my Solution, Visual Studio have added this:
![image](https://user-images.githubusercontent.com/1966285/61457923-c5ea2100-a93f-11e9-89d9-aa1601ef9383.png)

My goal is to run it on Linux with OpenShift platform, creating a docker image from source.
I'm supposed to copy the libwkhtmltox manually to my web project folder? Is there some configuration missing?

Thanks in advance

**Comment by Cr3ature** [comment]
Hey Leandro, I'll have a look at it, this evening. Normally the native libs are included. Been a long time since I used the code. Ported the code few months ago, but last use is almost a year ago. Non the less, I'll keep you posted.

**Comment by Cr3ature** [comment]
Hey Leandor,

Couldn't help myself and took a look at the issue.
I've released (1.0.2) containing a fix for the wrong file path construction (bug) that was in it. Everything works fine in a demo program that I quickly constructed, but gives problems when running from within a container. I haven't resolved the support for docker yet. But outside docker everything works.
I hope this is kinda an answer to your problem.

If any other, new or further detail question or request, what so ever... , don't hesistate to ask.

I'll keep you posted on progress on the docker support.

Grtz,
David

**Comment by drasalskis** [comment]
Hi, David,
I had the same issue, and found solution in DinkToPdf repo. 

"Create and call CustomAssemblyLoadContext before you create your converter"
https://github.com/rdvojmoc/DinkToPdf/issues/5#issuecomment-321183899

**Comment by Cr3ature** [comment]
Hey Drasalskis,

this was allready included. What addition did you do for path support for docker containers? Or wasn't this the issue at hand? https://github.com/Cr3ature/HtmlToPdfConverter/blob/master/Source/HtmlToPdfConverter.Core/Configuration/CustomAssemblyLoadContext.cs

There is a ServiceCollectionExtension that sets up the entire wrapper service:
services.AddHtmlToPdfConverterService();
